# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeadImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headimg', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timg', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=40)),
                ('unit', models.CharField(max_length=40)),
                ('wimg', models.CharField(max_length=40)),
                ('sold', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=30)),
                ('unit', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=60)),
                ('headimg', models.CharField(max_length=30)),
                ('midimg', models.CharField(max_length=30)),
                ('smallimg1', models.CharField(max_length=30)),
                ('smallimg2', models.CharField(max_length=30)),
                ('smallimg3', models.CharField(max_length=30)),
                ('smallimg4', models.CharField(max_length=30)),
                ('smallimg5', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='List2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=60)),
                ('unit', models.CharField(max_length=60)),
                ('text', models.CharField(max_length=60)),
                ('himg', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='List3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=60)),
                ('unit', models.CharField(max_length=60)),
                ('text', models.CharField(max_length=60)),
                ('himg', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='List4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=60)),
                ('unit', models.CharField(max_length=60)),
                ('text', models.CharField(max_length=60)),
                ('himg', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='List5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=60)),
                ('unit', models.CharField(max_length=60)),
                ('text', models.CharField(max_length=60)),
                ('himg', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
    ]
