# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
    ]
