# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handuapp', '0002_userm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserM',
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
