# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handuapp', '0003_hot'),
    ]

    operations = [
        migrations.CreateModel(
            name='List2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=60)),
                ('unit', models.CharField(max_length=60)),
                ('text', models.CharField(max_length=60)),
                ('himg', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='List3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=60)),
                ('unit', models.CharField(max_length=60)),
                ('text', models.CharField(max_length=60)),
                ('himg', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='List4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=60)),
                ('unit', models.CharField(max_length=60)),
                ('text', models.CharField(max_length=60)),
                ('himg', models.CharField(max_length=200)),
            ],
        ),
    ]
