# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handuapp', '0003_auto_20190115_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('isselect', models.BooleanField(default=True)),
                ('list1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handuapp.List')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handuapp.User')),
            ],
        ),
    ]
