# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handuapp', '0004_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('createtime', models.DateField(auto_now_add=True)),
                ('identifier', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handuapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('goos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handuapp.List')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handuapp.Order')),
            ],
        ),
    ]
