# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handuapp', '0005_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
