# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handuapp', '0005_order_ordergoods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordergoods',
            old_name='goos',
            new_name='goods',
        ),
    ]
